name: Batch

on:
  schedule:
    - cron: '25 14 * * *'
  workflow_dispatch:
jobs:
  run:
    name: Scheduled action
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - run: ls -al ..
      - run: ls -al ../..
      - run: ls -al ../../..
      - run: echo ${PWD}