name: Batch

on:
  schedule:
    - cron: '25 14 * * *'
  workflow_dispatch:
jobs:
  run:
    name: Scheduled action
    working-directory: cryptobot
    runs-on: ubuntu-latest
    steps:
      - name: run bf bot
        run: python bf_bot.py
