name: Batch

on:
  schedule:
    - cron: '25 14 * * *'
  workflow_dispatch:
jobs:
  run:
    name: Scheduled action
    runs-on: ubuntu-latest
    steps:
      - name: run bf bot
        run: echo ${PWD}
